//
// Created by cigan on 15.10.2020.
//

#ifndef PROBLEMSOLVINGARHITECTURE_VALIDATIONSIMPLEMENTATION_H
#define PROBLEMSOLVINGARHITECTURE_VALIDATIONSIMPLEMENTATION_H

#include "ValidationsDef.h"

#endif //PROBLEMSOLVINGARHITECTURE_VALIDATIONSIMPLEMENTATION_H
