//
// Created by cigan on 15.10.2020.
//

#ifndef PROBLEMSOLVINGARHITECTURE_DATASTRUCTURES_H
#define PROBLEMSOLVINGARHITECTURE_DATASTRUCTURES_H

#include "../CoreDependencies/CoreDependencies.h"

#endif //PROBLEMSOLVINGARHITECTURE_DATASTRUCTURES_H
