//
// Created by cigan on 15.10.2020.
//

#ifndef PROBLEMSOLVINGARHITECTURE_IOIMPLEMENTATION_H
#define PROBLEMSOLVINGARHITECTURE_IOIMPLEMENTATION_H

#include "IODef.h"

#endif //PROBLEMSOLVINGARHITECTURE_IOIMPLEMENTATION_H
