//
// Created by cigan on 15.10.2020.
//

#ifndef PROBLEMSOLVINGARHITECTURE_UNITTESTINGSUPPORTDEF_H
#define PROBLEMSOLVINGARHITECTURE_UNITTESTINGSUPPORTDEF_H

#include "../DataStructures/DataStructures.h"

#endif //PROBLEMSOLVINGARHITECTURE_UNITTESTINGSUPPORTDEF_H
