//
// Created by cigan on 15.10.2020.
//

#ifndef PROBLEMSOLVINGARHITECTURE_UNITTESTINGSUPPORTIMPLEMENTATION_H
#define PROBLEMSOLVINGARHITECTURE_UNITTESTINGSUPPORTIMPLEMENTATION_H

#include "UnitTestingSupportDef.h"

#endif //PROBLEMSOLVINGARHITECTURE_UNITTESTINGSUPPORTIMPLEMENTATION_H
